export const names = {
  "B zone": [
    "SAFWAN KDVLLY",
    "NAJEEB",
    "RAZI",
    "BISHR PALLAR",
    "AL AMEEN",
    "SHAMMAS",
    "THWAHA",
    "JASEEM",
    "SHADULI",
    "RESHNID",
    "Sayyid HASHBAL",
    "MINHAJ",
    "BARI",
    "MISHAB PYNR",
    "SWALIH",
    "HAKEEM",
    "RABEEH",
    "BISHR THATHOOR",
    "DAVOOD",
    "SHAMVEEL",
    "SAYYID BISHR ",

    "SAFVAN MLYMA ",
    "RAMEES",
    "SUFAIR",
    "ZUHAIR",
    "FAYAS",
    "MUHAMMAD VADAKARA",
    "UNAIS",
  ],
  "C zone": [
    "JUNAID",
    "SAFWAN TVM",
    "ZAINUL ABID",
    "SINAN AP",
    "SWABAH",
    "MUHSIN",
    "THAJUDHEEN",
    "HABEEB WYND",
    "FAKIH",
    "SHUAIB KTYDI",
    "MUSTHAFA VKD",
    "JUHAN",
    "SALMAN",
    "SINAN TVM",
    "NIHAL",
    "HABEEB",
    "YASEEN",
    "MUBASHIR",
    "FAVAS",
    "AMEEN THAHOOR",
    "SWALIH",
    "MISHAB TLSY",
    "S.KHUBAB",
    "FARHAN",
    "THASNEEM",
    "ZUHAIR",
    "SAJJAD",
    "HAFEEZ PLKD",
    "HAMID",
    "AMEEN TVM",
    "MUSTHAFA KOOFA",
    "AFSAL",
    "MUHAMMAD IYYAD",
    "NOUFAL",
    "SINAN NEW",
  ],
  "Y zone": [
    "SHURAHBEEL",
    "MUBARAK",
    " MUHAMMED ALIYAR",
    "YUNUS",
    "SHAHID",
    "AADIL",
    "SALMAN CHELARI",
    "SHUAIB PGY",
    "FAZLURAHMAN",
    "MUHAMMED HAMEED",
    "SAUD ANSARI",
    "RASHID",
    "AJEER",
    "LABEEB",
    "HIJAS",
    "NOUFAL",
    "SHAHABAS",
    "MANSOOR",
    "SALMAN TGI",
    "HARSHAD",
    "SHAMMAS",
    "NIHAL",
    "MUEEN",
    "BILAL",
    "SAHIL",
    "HAFEEZ",
    "AMEEN",
    "SAHAD",
    "ZIYAD",
    "UNAIS",
    "JUNAID KPM",
    "ASLAM KDY",
    "MUHAMMAD ALI PYNR",

    "ABU THWAHIR",
    "THAMEEM",
    "ASLAM EDAKKARA",
    "MUHAMAD ALI(TVM)",
    "MUHTHASIM",
    "SHAHEER",
    "SWALAHUDHEEN",
    "SHIBILY",
    "ANAS",
  ],
};
